#!/bin/bash
echo "🐘 PostgreSQL Installation Guide"
echo "================================"
echo ""
echo "Step 1: Fix Homebrew permissions (if needed)"
echo "sudo chown -R neil /opt/homebrew/Cellar"
echo ""
echo "Step 2: Install PostgreSQL"
echo "brew install postgresql@15"
echo ""
echo "Step 3: Start PostgreSQL service"
echo "brew services start postgresql@15"
echo ""
echo "Step 4: Create database"
echo "createdb merchant_tester"
echo ""
echo "Step 5: Update .env file with your password (if you set one)"
echo "The .env file is already created at:"
echo "$(pwd)/.env"
echo ""
echo "Step 6: Restart the server"
echo "npm start"
echo ""
echo "📝 Run each command manually or run: source INSTALL_POSTGRES.sh"
